# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qs2_get_compress_level <- function() {
    .Call(`_qs2_qs2_get_compress_level`)
}

qs2_set_compress_level <- function(value) {
    invisible(.Call(`_qs2_qs2_set_compress_level`, value))
}

qs2_get_shuffle <- function() {
    .Call(`_qs2_qs2_get_shuffle`)
}

qs2_set_shuffle <- function(value) {
    invisible(.Call(`_qs2_qs2_set_shuffle`, value))
}

qs2_get_nthreads <- function() {
    .Call(`_qs2_qs2_get_nthreads`)
}

qs2_set_nthreads <- function(value) {
    invisible(.Call(`_qs2_qs2_set_nthreads`, value))
}

qs2_get_validate_checksum <- function() {
    .Call(`_qs2_qs2_get_validate_checksum`)
}

qs2_set_validate_checksum <- function(value) {
    invisible(.Call(`_qs2_qs2_set_validate_checksum`, value))
}

qs2_get_warn_unsupported_types <- function() {
    .Call(`_qs2_qs2_get_warn_unsupported_types`)
}

qs2_set_warn_unsupported_types <- function(value) {
    invisible(.Call(`_qs2_qs2_set_warn_unsupported_types`, value))
}

qs2_get_use_alt_rep <- function() {
    .Call(`_qs2_qs2_get_use_alt_rep`)
}

qs2_set_use_alt_rep <- function(value) {
    invisible(.Call(`_qs2_qs2_set_use_alt_rep`, value))
}

qs_save <- function(object, file, compress_level = qopt("compress_level"), shuffle = qopt("shuffle"), nthreads = qopt("nthreads")) {
    invisible(.Call(`_qs2_qs_save`, object, file, compress_level, shuffle, nthreads))
}

qs_serialize <- function(object, compress_level = qopt("compress_level"), shuffle = qopt("shuffle"), nthreads = qopt("nthreads")) {
    invisible(.Call(`_qs2_qs_serialize`, object, compress_level, shuffle, nthreads))
}

qs_read <- function(file, validate_checksum = qopt("validate_checksum"), nthreads = qopt("nthreads")) {
    .Call(`_qs2_qs_read`, file, validate_checksum, nthreads)
}

qs_deserialize <- function(input, validate_checksum = qopt("validate_checksum"), nthreads = qopt("nthreads")) {
    .Call(`_qs2_qs_deserialize`, input, validate_checksum, nthreads)
}

qd_save <- function(object, file, compress_level = qopt("compress_level"), shuffle = qopt("shuffle"), warn_unsupported_types = qopt("warn_unsupported_types"), nthreads = qopt("nthreads")) {
    invisible(.Call(`_qs2_qd_save`, object, file, compress_level, shuffle, warn_unsupported_types, nthreads))
}

qd_serialize <- function(object, compress_level = qopt("compress_level"), shuffle = qopt("shuffle"), warn_unsupported_types = qopt("warn_unsupported_types"), nthreads = qopt("nthreads")) {
    .Call(`_qs2_qd_serialize`, object, compress_level, shuffle, warn_unsupported_types, nthreads)
}

qd_read <- function(file, use_alt_rep = qopt("use_alt_rep"), validate_checksum = qopt("validate_checksum"), nthreads = qopt("nthreads")) {
    .Call(`_qs2_qd_read`, file, use_alt_rep, validate_checksum, nthreads)
}

qd_deserialize <- function(input, use_alt_rep = qopt("use_alt_rep"), validate_checksum = qopt("validate_checksum"), nthreads = qopt("nthreads")) {
    .Call(`_qs2_qd_deserialize`, input, use_alt_rep, validate_checksum, nthreads)
}

qx_dump <- function(file) {
    .Call(`_qs2_qx_dump`, file)
}

check_SIMD <- function() {
    .Call(`_qs2_check_SIMD`)
}

check_TBB <- function() {
    .Call(`_qs2_check_TBB`)
}

check_internal_blocksize <- function() {
    .Call(`_qs2_check_internal_blocksize`)
}

internal_set_blocksize <- function(size) {
    .Call(`_qs2_internal_set_blocksize`, size)
}

internal_is_utf8_locale <- function(size) {
    .Call(`_qs2_internal_is_utf8_locale`, size)
}

zstd_compress_raw <- function(data, compress_level = qopt("compress_level")) {
    .Call(`_qs2_zstd_compress_raw`, data, compress_level)
}

zstd_decompress_raw <- function(data) {
    .Call(`_qs2_zstd_decompress_raw`, data)
}

zstd_compress_bound <- function(size) {
    .Call(`_qs2_zstd_compress_bound`, size)
}

blosc_shuffle_raw <- function(data, bytesofsize) {
    .Call(`_qs2_blosc_shuffle_raw`, data, bytesofsize)
}

blosc_unshuffle_raw <- function(data, bytesofsize) {
    .Call(`_qs2_blosc_unshuffle_raw`, data, bytesofsize)
}

xxhash_raw <- function(data) {
    .Call(`_qs2_xxhash_raw`, data)
}

base85_encode <- function(rawdata) {
    .Call(`_qs2_base85_encode`, rawdata)
}

base85_decode <- function(encoded_string) {
    .Call(`_qs2_base85_decode`, encoded_string)
}

c_base91_encode <- function(rawdata) {
    .Call(`_qs2_c_base91_encode`, rawdata)
}

c_base91_decode <- function(encoded_string) {
    .Call(`_qs2_c_base91_decode`, encoded_string)
}

zstd_compress_file <- function(input_file, output_file, compress_level = qopt("compress_level")) {
    invisible(.Call(`_qs2_zstd_compress_file`, input_file, output_file, compress_level))
}

zstd_decompress_file <- function(input_file, output_file) {
    invisible(.Call(`_qs2_zstd_decompress_file`, input_file, output_file))
}

