# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qs_save <- function(object, file, compress_level = 3L, shuffle = TRUE, nthreads = 1L) {
    invisible(.Call(`_qs2_qs_save`, object, file, compress_level, shuffle, nthreads))
}

qs_read <- function(file, nthreads = 1L) {
    .Call(`_qs2_qs_read`, file, nthreads)
}

qd_save <- function(object, file, compress_level = 3L, shuffle = TRUE, warn = TRUE, nthreads = 1L) {
    invisible(.Call(`_qs2_qd_save`, object, file, compress_level, shuffle, warn, nthreads))
}

qd_read <- function(file, use_alt_rep = FALSE, nthreads = 1L) {
    .Call(`_qs2_qd_read`, file, use_alt_rep, nthreads)
}

