# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qs_save <- function(object, file, compress_level = 3L, shuffle = TRUE, nthreads = 1L) {
    invisible(.Call(`_qs2_qs_save`, object, file, compress_level, shuffle, nthreads))
}

qs_read <- function(file, validate_checksum = FALSE, nthreads = 1L) {
    .Call(`_qs2_qs_read`, file, validate_checksum, nthreads)
}

qd_save <- function(object, file, compress_level = 3L, shuffle = TRUE, warn_unsupported_types = TRUE, nthreads = 1L) {
    invisible(.Call(`_qs2_qd_save`, object, file, compress_level, shuffle, warn_unsupported_types, nthreads))
}

qd_read <- function(file, use_alt_rep = FALSE, validate_checksum = TRUE, nthreads = 1L) {
    .Call(`_qs2_qd_read`, file, use_alt_rep, validate_checksum, nthreads)
}

qx_dump <- function(file) {
    .Call(`_qs2_qx_dump`, file)
}

check_SIMD <- function() {
    .Call(`_qs2_check_SIMD`)
}

check_TBB <- function() {
    .Call(`_qs2_check_TBB`)
}

check_internal_blocksize <- function() {
    .Call(`_qs2_check_internal_blocksize`)
}

zstd_compress_raw <- function(data, compress_level) {
    .Call(`_qs2_zstd_compress_raw`, data, compress_level)
}

zstd_decompress_raw <- function(data) {
    .Call(`_qs2_zstd_decompress_raw`, data)
}

zstd_compress_bound <- function(size) {
    .Call(`_qs2_zstd_compress_bound`, size)
}

blosc_shuffle_raw <- function(data, bytesofsize) {
    .Call(`_qs2_blosc_shuffle_raw`, data, bytesofsize)
}

blosc_unshuffle_raw <- function(data, bytesofsize) {
    .Call(`_qs2_blosc_unshuffle_raw`, data, bytesofsize)
}

