# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# NOTE: This workflow is overkill for most R packages and
# check-standard.yaml is likely a better choice.
# usethis::use_github_action("check-standard") will install it.
on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]

name: R-CMD-check

permissions:
  contents: read

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.name }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {name: 'macOS-latest (devel, system zstd)',   os: macOS-latest,   r: 'devel',   http-user-agent: 'release', install-args: ''}
          - {name: 'macOS-latest (release, system zstd)', os: macOS-latest,   r: 'release', install-args: ''}
          - {name: 'macOS-latest (release, bundled zstd)', os: macOS-latest,  r: 'release', install-args: '--configure-args=--with-zstd-force-compile'}
          - {name: 'windows-latest (devel)',              os: windows-latest, r: 'devel',   http-user-agent: 'release', install-args: ''}
          - {name: 'windows-latest (release)',            os: windows-latest, r: 'release', install-args: ''}
          - {name: 'ubuntu-latest (devel, system zstd)',  os: ubuntu-latest,  r: 'devel',   http-user-agent: 'release', install-args: ''}
          - {name: 'ubuntu-latest (release, system zstd)', os: ubuntu-latest, r: 'release', install-args: ''}
          - {name: 'ubuntu-latest (release, bundled zstd)', os: ubuntu-latest, r: 'release', install-args: '--configure-args=--with-zstd-force-compile'}
          - {name: 'ubuntu-latest (oldrel-1)',            os: ubuntu-latest,  r: 'oldrel-1', install-args: ''}
          - {name: 'ubuntu-latest (oldrel-2)',            os: ubuntu-latest,  r: 'oldrel-2', install-args: ''}
          - {name: 'ubuntu-latest (oldrel-3)',            os: ubuntu-latest,  r: 'oldrel-3', install-args: ''}
          - {name: 'ubuntu-latest (oldrel-4)',            os: ubuntu-latest,  r: 'oldrel-4', install-args: ''}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      QS_EXTENDED_TESTS: true

    steps:
      - name: Windows CRLF fix
        run: git config --global core.autocrlf false

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - if: runner.os == 'macOS' && matrix.config.r == 'devel'
        run: sudo Rscript -e 'source("https://mac.R-project.org/bin/install.R"); install.libs("gettext")'


      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - if: matrix.config.install-args == ''
        uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--as-cran")'
          upload-snapshots: true

      - if: matrix.config.install-args != ''
        uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--as-cran", "--install-args=${{ matrix.config.install-args }}")'
          upload-snapshots: true
